services:
    _defaults:
        autowire: true
        bind:
            $root_path: '%core.root_path%'
            $tables: '%tables%'
    dmzx.missingfiles.controller.acp:
        class: 'dmzx\missingfiles\controller\acp_controller'